export type TaskStatus = 'To Do' | 'In Progress' | 'Completed';
export type TaskPriority = 'Low' | 'Medium' | 'High';

export interface Task {
  id: string; // Document ID (auto-generated by Firestore)
  title: string;
  description: string;
  status: TaskStatus;
  priority: TaskPriority;
  dueDate: string; // ISO 8601 string or YYYY-MM-DD format
  createdAt: string; // ISO 8601 string timestamp
  teamId?: string | null; // For Practical Exam 2
  assigneeId?: string | null; // For Practical Exam 2
}

export interface CreateTaskInput {
  title: string;
  description?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  dueDate?: string;
  teamId?: string | null;
  assigneeId?: string | null;
}

export interface UpdateTaskInput {
  title?: string;
  description?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  dueDate?: string;
  teamId?: string | null;
  assigneeId?: string | null;
}
